version: "3.7"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_database_container
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: project_db

volumes:
  mysql-data:
