server:
  error:
    include-message: always
    include-stacktrace: never
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/test
